### PR TITLE
Add link to colour contrast checker

### PR DESCRIPTION
**Pull request by NickColley**
Quick and dirty

Adds a link to http://leaverou.github.io/contrast-ratio/#white-on-purple so people can check their colours are readable

screen shot 2017-06-22 at 14 09 27

### CODE REVIEW

**Review by govuklaurence — CHANGES_REQUESTED** [review]
Can you stick the link below so it doesn't split the label and the field?

**Comment by govuklaurence** [comment]
Or inline with the label

**Comment by NickColley** [comment]
Sure this follows our patterns tho' https://govuk-elements.herokuapp.com/form-elements/#form-hint-text

**Review by govuklaurence — APPROVED** [review]

**Comment by NickColley** [comment]
screen shot 2017-06-22 at 14 45 31

**Pull request merged**
